name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Устанавливаем pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      # 2. Настраиваем Node.js и включаем кэш для pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 3. Ставим зависимости
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4. Собираем Nuxt
      - name: Build project
        run: pnpm build

      # 5. Загружаем билд как артефакт
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
